name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'      # Updated to Java 17 to match pom.xml

    - name: Build with Maven
      run: mvn clean install

    - name: Rename JAR for Docker
      run: mv target/WiproDCS1-1.0-SNAPSHOT.jar target/app.jar

    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set lowercase image name
      run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Docker Build
      run: docker build -t $IMAGE_NAME .
